### ISSUE TITLE
Bootstrap.sh fails with 7.7_202005 release

### ISSUE THREAD

**Issue by snon-axway** [Axway-API-Management-Plus/filter-devkit#4]
Due to duplicate classes in 7.7_202005 release, it seems that bootstrap.sh script fails while trying to create the server archive 

> Create server runtime archive
> adding file 'apiportal.jar' to server runtime
> adding file 'circuit.jar' to server runtime
> adding file 'client.jar' to server runtime
> adding file 'coercers.jar' to server runtime
> adding file 'common.jar' to server runtime
> adding file 'jwkjose.jar' to server runtime
> adding file 'logger.jar' to server runtime
> adding file 'manager.jar' to server runtime
> adding file 'oauthclient.jar' to server runtime
> adding file 'openidconnect.jar' to server runtime
> adding file 'precipitate.jar' to server runtime
> adding file 'security.jar' to server runtime
> adding file 'server.jar' to server runtime
> adding file 'testClient.jar' to server runtime
> adding file 'upgrade.jar' to server runtime
> adding file 'wspolicy.jar' to server runtime
> adding file 'xmlutils.jar' to server runtime
> adding file 'com.vordel.jms.jar' to server runtime
> adding file 'com.vordel.circuit.tibco.jar' to server runtime
> adding file 'com.vordel.circuit.conversion.jar' to server runtime
> adding file 'com.vordel.circuit.throttling.jar' to server runtime
> adding file 'com.vordel.circuit.log.jar' to server runtime
> adding file 'com.vordel.circuit.wstrust.jar' to server runtime
> adding file 'com.vordel.circuit.format-7.7.0.20200530-2.jar' to server runtime
> unexpected exception
> GatewayMavenizer <vdistdir> [policystudiodir]

When using debug mode, the script fails while processing 'com.vordel.circuit.format-7.7.0.20200530-2.jar' in the addRuntimeArchive method.
The following class com/vordel/common/util/WildcardedString.class cannot be added with out.putNextEntry(item); and fails with the following exception :
duplicate entry: com/vordel/common/util/WildcardedString.class

Kind regards,
Sovanna

**Comment by rathnapandi** [comment]
WildcardedString.class file is duplicated in two jars. 

- apigateway/system/lib/com.vordel.circuit.format-7.7.0.20200530-2.jar matches
- apigateway/common.jar matches


I moved the file com.vordel.circuit.format-7.7.0.20200530-2.jar from apigateway/system/lib to temp location and run the bootstrap script. Once bootstrap script is completed move the jar back to apigateway/system/lib folder.

**Comment by rdesaintleger** [comment]
Corrected in commit https://github.com/Axway-API-Management-Plus/filter-devkit/commit/749ad35f1215ec3b419788526bc272dda0e3d81d 

A hash is now done on each added file. Duplicates are detected and skipped. Actually in develop, will be soon in master.
