### ISSUE TITLE
Support V7.7 May Release

### ISSUE THREAD

**Issue by rathnapandi** [Axway-API-Management-Plus/filter-devkit#5]
Due to changes in apigateway internal APIs the code is not working.

**Comment by rdesaintleger** [comment]
A Fix with 7.5.x compatible code has been done to support 7.7 May release on develop branch

KPS Resource Fix : https://github.com/Axway-API-Management-Plus/filter-devkit/commit/c3dff9f89968f4ed72cff414f188e8008ad1041e (use reflection access)
IStoreAccess Fix https://github.com/Axway-API-Management-Plus/filter-devkit/commit/b1c396a1136571901ea551b23f1a6461516d11e1 (taken from pull request)

 Actually in develop branch, soon in master.
